blank_issues_enabled: false
contact_links:
  - name: Security reports
    url: https://github.com/CarlDeanClineSr/LUFT-Auto/security/policy
    about: Please report vulnerabilities privately via the Security policy.
