blank_issues_enabled: false
contact_links:
  - name: Security reports
    url: https://github.com/CarlDeanClineSr/LUFT-Auto/security/advisories
    about: Please report security vulnerabilities via GitHub Security Advisories.