name: Auto Index (docs/INDEX.md)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build docs/INDEX.md
        run: |
          python3 scripts/auto_index_repo.py
      - name: Create Pull Request with changes
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(index): auto-update docs/INDEX.md"
          title: "chore(index): auto-update docs/INDEX.md"
          branch: ci/auto-index
          delete-branch: true
          add-paths: |
            docs/INDEX.md
