name: Auto Update via PR

on:
  workflow_dispatch:
  schedule:
    - cron: '17 10 * * *' # daily at 10:17 UTC; adjust as needed

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: auto-update-main
  cancel-in-progress: true

jobs:
  auto_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Configure git identity
        run: |
          git config user.name "LUFT-AutoBot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Optional project-specific update script
        run: |
          if [ -x scripts/auto_update.sh ]; then
            bash scripts/auto_update.sh
          else
            echo "No scripts/auto_update.sh present; skipping project-specific changes."
          fi

      - name: Commit changes (if any)
        id: commit
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            git add -A
            git commit -m "Auto-update: routine maintenance [skip ci]"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create or update PR
        if: steps.commit.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: autobot/auto-update
          title: "Auto-update: routine maintenance"
          body: |
            This PR was created automatically to apply routine maintenance updates (manifests, indexes, docs, logs, etc.).

            - Opened by: GitHub Actions (LUFT-AutoBot)
            - Safe mode: Uses PRs instead of pushing directly to main to avoid collisions
            - Commit includes [skip ci] to avoid recursive triggers

            Please review and merge when convenient. Repo Guardian will remind us if it sits here too long.
          labels: auto-update, bot
          commit-message: "Auto-update: routine maintenance [skip ci]"
          signoff: false
          delete-branch: true
