name: Codex Miner Weekly
on:
  schedule:
    - cron: "0 9 * * 1"  # Mondays 09:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-miner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
          pip install -r tools/requirements.txt || true
      - name: Run knowledge miner
        run: |
          python tools/knowledge_miner.py --config codex/config.yaml
      - name: Commit changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain codex)" ]]; then
            git add codex/
            git commit -m "chore(codex): weekly knowledge miner update"
            git push
          else
            echo "No changes to commit."
          fi
